### ISSUE TITLE
CC3200 EMT — Create a specific CC3200 EMT repository for issue tracking 

### ISSUE THREAD

**Issue by robertinant** [energia/cc3200emt-core#4]
_From @rei-vilo on December 21, 2016 13:26_

Please create a specific CC3200 EMT repository for issue tracking.

_Copied from original issue: energia/cc3200-core#11_

**Comment by robertinant** [comment]
_From @rei-vilo on December 21, 2016 13:27_

Affected issues #6 #8 #9 #10.

**Comment by robertinant** [comment]
done: https://github.com/energia/cc3200emt-core

**Comment by rei-vilo** [comment]
This issue can be closed now. I don't have the credentials on this repository for closing it myself. Thank you.
